name: Build midi2usbhub UF2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi g++ build-essential libusb-1.0-0-dev

    - name: Setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git --branch 2.0.0
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV

    - name: Verify libusb installation
      run: |
        ls -l /usr/include/libusb-1.0/libusb.h || echo "libusb.h not found"
        ls -l /usr/lib/x86_64-linux-gnu/libusb-1.0.so || echo "libusb-1.0.so not found"

    - name: Ensure submodules are initialized
      run: |
        git submodule sync --recursive
        git submodule update --init --recursive
        # Manual cloning if submodules are missing
        [ -d "lib/tinyusb" ] || git clone https://github.com/hathach/tinyusb.git lib/tinyusb
        [ -d "lib/usb_midi_host" ] || git clone https://github.com/rppicomidi/usb_midi_host.git lib/usb_midi_host
        ls -ld lib/tinyusb || echo "tinyusb still not found"
        ls -ld lib/usb_midi_host || echo "usb_midi_host still not found"

    - name: Build project
      run: |
        # Patch CMakeLists.txt to include TinyUSB
        sed -i '/add_subdirectory(${CMAKE_CURRENT_LIST_DIR}\/lib\/usb_midi_host)/i add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/lib/tinyusb lib/tinyusb)' CMakeLists.txt
        cat CMakeLists.txt
        
        mkdir -p build
        cd build
        rm -rf *
        cmake .. -DPICO_BOARD=pico -DPICO_SDK_PATH=${{ env.PICO_SDK_PATH }} -DCMAKE_FRESH=ON
        make

    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: midi2usbhub.uf2
        path: build/midi2usbhub.uf2
