name: Build midi2usbhub UF2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi g++ build-essential libusb-1.0-0-dev

    - name: Setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git --branch 2.0.0
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV

    - name: Verify libusb installation
      run: |
        echo "Checking libusb include path:"
        ls -l /usr/include/libusb-1.0/libusb.h || echo "libusb.h not found"
        echo "Checking libusb library path:"
        ls -l /usr/lib/x86_64-linux-gnu/libusb-1.0.so || echo "libusb-1.0.so not found"

    - name: Modify CMakeLists.txt to force libusb detection
      run: |
        sed -i '/find_library(LIBUSB_LIBRARY NAMES usb-1.0 libusb-1.0)/i set(LIBUSB_LIBRARY "/usr/lib/x86_64-linux-gnu/libusb-1.0.so" CACHE FILEPATH "Path to libusb library" FORCE)' CMakeLists.txt
        sed -i '/find_path(LIBUSB_INCLUDE_DIR NAMES libusb.h PATH_SUFFIXES libusb-1.0)/i set(LIBUSB_INCLUDE_DIR "/usr/include/libusb-1.0" CACHE PATH "Path to libusb include dir" FORCE)' CMakeLists.txt
        sed -i 's/message(STATUS "libUSB is not found - no USB support will be built")/# Removed: message(STATUS "libUSB is not found - no USB support will be built")/' CMakeLists.txt
        sed -i 's/if(LIBUSB_LIBRARY AND LIBUSB_INCLUDE_DIR)/if(1)/' CMakeLists.txt

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake .. -DPICO_BOARD=pico -DPICO_SDK_PATH=${{ env.PICO_SDK_PATH }} \
          -DCMAKE_VERBOSE_MAKEFILE=ON -DCMAKE_FRESH=ON
        make

    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: midi2usbhub.uf2
        path: build/midi2usbhub.uf2
