name: Build midi2usbhub UF2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi g++ build-essential

    - name: Setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git --branch 2.0.0
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV  # Setzt die Umgebungsvariable für nachfolgende Schritte

    - name: Build the project
      run: |
        mkdir build
        cd build
        cmake .. -DPICO_BOARD=pico -DPICO_SDK_PATH=${{ env.PICO_SDK_PATH }}
        make

    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: midi2usbhub.uf2
        path: build/midi2usbhub.uf2
