name: Build midi2usbhub UF2

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y cmake gcc-arm-none-eabi g++ build-essential libusb-1.0-0-dev

    - name: Setup Pico SDK
      run: |
        git clone https://github.com/raspberrypi/pico-sdk.git --branch 2.0.0
        cd pico-sdk
        git submodule update --init
        echo "PICO_SDK_PATH=$(pwd)" >> $GITHUB_ENV

    - name: Verify libusb installation
      run: |
        ls -l /usr/include/libusb-1.0/libusb.h || echo "libusb.h not found"
        ls -l /usr/lib/x86_64-linux-gnu/libusb-1.0.so || echo "libusb-1.0.so not found"

    - name: Modify and build project
      run: |
        # Replace the entire libusb block
        sed -i '/find_library(LIBUSB_LIBRARY NAMES usb-1.0 libusb-1.0)/,/endif()/c\
        set(LIBUSB_LIBRARY "/usr/lib/x86_64-linux-gnu/libusb-1.0.so" CACHE FILEPATH "Path to libusb library" FORCE)\n\
        set(LIBUSB_INCLUDE_DIR "/usr/include/libusb-1.0" CACHE PATH "Path to libusb include dir" FORCE)\n\
        message(STATUS "libUSB forced - building with USB support")\n\
        add_definitions(-DUSE_USB=1)\n\
        target_include_directories(${PROJECT_NAME} PRIVATE ${LIBUSB_INCLUDE_DIR})\n\
        target_link_libraries(${PROJECT_NAME} ${LIBUSB_LIBRARY})' CMakeLists.txt
        echo "CMakeLists.txt after modification:"
        cat CMakeLists.txt
        
        # Build immediately in the same step
        mkdir -p build
        cd build
        rm -rf *  # Clear any existing cache
        echo "CMakeLists.txt before cmake:"
        cat ../CMakeLists.txt
        cmake .. -DPICO_BOARD=pico -DPICO_SDK_PATH=${{ env.PICO_SDK_PATH }} -DCMAKE_FRESH=ON
        make

    - name: Upload UF2 artifact
      uses: actions/upload-artifact@v4
      with:
        name: midi2usbhub.uf2
        path: build/midi2usbhub.uf2
